In [1]:
from graphviz import Source
from IPython.display import Image
from google.colab import drive

drive.mount('/content/drive')
%cd /content/drive/Shareddrives/Data/밑바닥부터 시작하는 딥러닝

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/Shareddrives/Data/밑바닥부터 시작하는 딥러닝


# Step 37

In [2]:
import numpy as np
import dezero.functions as F
from dezero import Variable as v

x = v(np.array([[1,2,3],[4,5,6]]))
y = F.sin(x)
print(y)

variable([[ 0.84147098  0.90929743  0.14112001]
          [-0.7568025  -0.95892427 -0.2794155 ]])


In [3]:
x = v(np.array([[1,2,3],[4,5,6]]))
c = v(np.array([[10,20,30],[40,50,60]]))
t = x + c
y = F.sum(t)
print(y)

variable(231)


# Step 38

In [4]:
import numpy as np
from dezero import Variable as v
import dezero.functions as F

x = v(np.array([[1,2,3],[4,5,6]]))
y = F.reshape(x, (6,))
y.backward(retain_grad=True)
print(x.grad)

variable([[1 1 1]
          [1 1 1]])


In [5]:
x = v(np.random.randn(1,2,3))
y = x.reshape((2,3))
y = x.reshape(2,3)

In [6]:
x = v(np.array([[1,2,3],[4,5,6]]))
y = F.transpose(x)
print(y)
y.backward()
print(x.grad)

variable([[1 4]
          [2 5]
          [3 6]])
variable([[1 1 1]
          [1 1 1]])


In [7]:
x = v(np.array([[1,2,3],[4,5,6]]))
y = x.transpose()   # variable class의 def transpose 사용
z = x.T     # variable class의 @property def T 사용
print(y)
print(z)

variable([[1 4]
          [2 5]
          [3 6]])
variable([[1 4]
          [2 5]
          [3 6]])


# Step 39

In [8]:
import numpy as np
from dezero import Variable as v
import dezero.functions as F

x = v(np.array([[1,2,3],[4,5,6]]))
y = F.sum(x)
y.backward()
print(y)
print(x.grad)

variable(21)
variable([[1 1 1]
          [1 1 1]])


In [9]:
x = v(np.random.randn(2,3,4,5))
y = x.sum(keepdims=True)
print(y.shape)

(1, 1, 1, 1)


# Step 40

In [10]:
import numpy as np
from dezero.utils import sum_to

x = np.array([[1,2,3,],[4,5,6]])
y = sum_to(x, (1, 3))
print(y)

y = sum_to(x, (2, 1))
print(y)

[[5 7 9]]
[[ 6]
 [15]]


In [11]:
from dezero import Variable as v

x0 = v(np.array([1,2,3]))
x1 = v(np.array([10]))
y = x0 + x1
print(y)

y.backward()
print(x1.grad)  

variable([11 12 13])
variable([3])
